// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RobotBarApp.DAL;

#nullable disable

namespace RobotBarApp.Migrations
{
    [DbContext(typeof(RobotBarContext))]
    partial class RobotBarContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("RobotBarApp.BE.BarSetup", b =>
                {
                    b.Property<Guid>("EventBarSetupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PositionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("EventBarSetupId");

                    b.HasIndex("EventId");

                    b.HasIndex("IngredientId");

                    b.ToTable("BarSetups");
                });

            modelBuilder.Entity("RobotBarApp.BE.DoubleScript", b =>
                {
                    b.Property<Guid>("ScriptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UrScript")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ScriptId");

                    b.HasIndex("IngredientId");

                    b.ToTable("DoubleScripts");
                });

            modelBuilder.Entity("RobotBarApp.BE.Drink", b =>
                {
                    b.Property<Guid>("DrinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMocktail")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DrinkId");

                    b.ToTable("Drinks");
                });

            modelBuilder.Entity("RobotBarApp.BE.DrinkContent", b =>
                {
                    b.Property<Guid>("DrinkContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Dose")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DrinkId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("TEXT");

                    b.HasKey("DrinkContentId");

                    b.HasIndex("DrinkId");

                    b.HasIndex("IngredientId");

                    b.ToTable("DrinkContents");
                });

            modelBuilder.Entity("RobotBarApp.BE.DrinkScript", b =>
                {
                    b.Property<Guid>("ScriptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DrinkId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UrScript")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ScriptId");

                    b.HasIndex("DrinkId");

                    b.ToTable("DrinkScripts");
                });

            modelBuilder.Entity("RobotBarApp.BE.DrinkUseCount", b =>
                {
                    b.Property<Guid>("UseCountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DrinkId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("UseCountId");

                    b.HasIndex("DrinkId");

                    b.HasIndex("EventId");

                    b.ToTable("DrinkUseCounts");
                });

            modelBuilder.Entity("RobotBarApp.BE.Event", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MenuId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EventId");

                    b.HasIndex("MenuId")
                        .IsUnique();

                    b.ToTable("Events");
                });

            modelBuilder.Entity("RobotBarApp.BE.Ingredient", b =>
                {
                    b.Property<Guid>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IngredientId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("RobotBarApp.BE.IngredientPosition", b =>
                {
                    b.Property<Guid>("IngredientPositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.HasKey("IngredientPositionId");

                    b.HasIndex("IngredientId");

                    b.ToTable("IngredientPositions");
                });

            modelBuilder.Entity("RobotBarApp.BE.IngredientUseCount", b =>
                {
                    b.Property<Guid>("UseCountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("UseCountId");

                    b.HasIndex("EventId");

                    b.HasIndex("IngredientId");

                    b.ToTable("IngredientUseCounts");
                });

            modelBuilder.Entity("RobotBarApp.BE.Log", b =>
                {
                    b.Property<Guid>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogMsg")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LogId");

                    b.HasIndex("EventId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("RobotBarApp.BE.Menu", b =>
                {
                    b.Property<Guid>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MenuId");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("RobotBarApp.BE.MenuContent", b =>
                {
                    b.Property<Guid>("MenuContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DrinkId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("TEXT");

                    b.HasKey("MenuContentId");

                    b.HasIndex("DrinkId");

                    b.HasIndex("MenuId");

                    b.ToTable("MenuContents");
                });

            modelBuilder.Entity("RobotBarApp.BE.SingleScript", b =>
                {
                    b.Property<Guid>("ScriptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UrScript")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ScriptId");

                    b.HasIndex("IngredientId");

                    b.ToTable("SingleScripts");
                });

            modelBuilder.Entity("RobotBarApp.BE.Sop", b =>
                {
                    b.Property<Guid>("SopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SopId");

                    b.ToTable("Sops");
                });

            modelBuilder.Entity("RobotBarApp.BE.SopStep", b =>
                {
                    b.Property<Guid>("SopStepsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SopId")
                        .HasColumnType("TEXT");

                    b.Property<int>("StepCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("SopStepsId");

                    b.HasIndex("SopId");

                    b.ToTable("SopSteps");
                });

            modelBuilder.Entity("RobotBarApp.BE.BarSetup", b =>
                {
                    b.HasOne("RobotBarApp.BE.Event", "Event")
                        .WithMany("BarSetups")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RobotBarApp.BE.Ingredient", "Ingredient")
                        .WithMany("BarSetups")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("RobotBarApp.BE.DoubleScript", b =>
                {
                    b.HasOne("RobotBarApp.BE.Ingredient", "Ingredient")
                        .WithMany("DoubleScripts")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("RobotBarApp.BE.DrinkContent", b =>
                {
                    b.HasOne("RobotBarApp.BE.Drink", "Drink")
                        .WithMany("DrinkContents")
                        .HasForeignKey("DrinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RobotBarApp.BE.Ingredient", "Ingredient")
                        .WithMany("DrinkContents")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Drink");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("RobotBarApp.BE.DrinkScript", b =>
                {
                    b.HasOne("RobotBarApp.BE.Drink", "Drink")
                        .WithMany("DrinkScripts")
                        .HasForeignKey("DrinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drink");
                });

            modelBuilder.Entity("RobotBarApp.BE.DrinkUseCount", b =>
                {
                    b.HasOne("RobotBarApp.BE.Drink", "drink")
                        .WithMany("DrinkUseCounts")
                        .HasForeignKey("DrinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RobotBarApp.BE.Event", "Event")
                        .WithMany("DrinkUseCounts")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("drink");
                });

            modelBuilder.Entity("RobotBarApp.BE.Event", b =>
                {
                    b.HasOne("RobotBarApp.BE.Menu", "Menu")
                        .WithOne("Event")
                        .HasForeignKey("RobotBarApp.BE.Event", "MenuId");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("RobotBarApp.BE.IngredientPosition", b =>
                {
                    b.HasOne("RobotBarApp.BE.Ingredient", "Ingredient")
                        .WithMany("IngredientPositions")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("RobotBarApp.BE.IngredientUseCount", b =>
                {
                    b.HasOne("RobotBarApp.BE.Event", "Event")
                        .WithMany("IngredientUseCounts")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RobotBarApp.BE.Ingredient", "Ingredient")
                        .WithMany("IngredientUseCounts")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("RobotBarApp.BE.Log", b =>
                {
                    b.HasOne("RobotBarApp.BE.Event", "Event")
                        .WithMany("Logs")
                        .HasForeignKey("EventId");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("RobotBarApp.BE.MenuContent", b =>
                {
                    b.HasOne("RobotBarApp.BE.Drink", "Drink")
                        .WithMany("MenuContents")
                        .HasForeignKey("DrinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RobotBarApp.BE.Menu", "Menu")
                        .WithMany("MenuContents")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drink");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("RobotBarApp.BE.SingleScript", b =>
                {
                    b.HasOne("RobotBarApp.BE.Ingredient", "Ingredient")
                        .WithMany("SingleScripts")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("RobotBarApp.BE.SopStep", b =>
                {
                    b.HasOne("RobotBarApp.BE.Sop", "Sop")
                        .WithMany("SopSteps")
                        .HasForeignKey("SopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sop");
                });

            modelBuilder.Entity("RobotBarApp.BE.Drink", b =>
                {
                    b.Navigation("DrinkContents");

                    b.Navigation("DrinkScripts");

                    b.Navigation("DrinkUseCounts");

                    b.Navigation("MenuContents");
                });

            modelBuilder.Entity("RobotBarApp.BE.Event", b =>
                {
                    b.Navigation("BarSetups");

                    b.Navigation("DrinkUseCounts");

                    b.Navigation("IngredientUseCounts");

                    b.Navigation("Logs");
                });

            modelBuilder.Entity("RobotBarApp.BE.Ingredient", b =>
                {
                    b.Navigation("BarSetups");

                    b.Navigation("DoubleScripts");

                    b.Navigation("DrinkContents");

                    b.Navigation("IngredientPositions");

                    b.Navigation("IngredientUseCounts");

                    b.Navigation("SingleScripts");
                });

            modelBuilder.Entity("RobotBarApp.BE.Menu", b =>
                {
                    b.Navigation("Event")
                        .IsRequired();

                    b.Navigation("MenuContents");
                });

            modelBuilder.Entity("RobotBarApp.BE.Sop", b =>
                {
                    b.Navigation("SopSteps");
                });
#pragma warning restore 612, 618
        }
    }
}
